---
title: "All_Genre_Pollstar"
author: "Alyssa"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up 

```{r, echo=FALSE, warning= FALSE, message = FALSE}
#read csv file
library(readr)
library(tidyverse)
# %>%
library(dplyr)
#plotting
library(ggplot2)
#modeling
library(Stat2Data)
#vif
library(car)
#corrplot
library(corrplot)
#Cross validation
library(Metrics)

```

revised csv
  - removed na
  - renamed variables
```{r, eval = F}

df <- read_csv('combined_df.csv', show_col_types = FALSE)



invalid_min <- df[df$`Ticket Price Min USD` >= df$`Ticket Price Max USD` | df$`Ticket Price Min USD` <= 0,]

df1 <- df %>% 
  filter(
    Year >= 2020,
    !str_detect(Headliner, '"'),
    Genre != 'Family Entertainment'
  ) 
df1 <- anti_join(df1, invalid_min, by = names(invalid_min))
summary(df1)

write_csv(df1,'all_genre_training.csv')

df2<- na.omit(df1)

```

```{r}
set.seed(42)
cut_index = nrow(df2) * 0.3
test_set = df2[0: cut_index,]
train_set = anti_join(df1, test_set, by = names(df1))

print(sprintf("Total filtered data: %d", nrow(df1)))
print(sprintf("Test set size: %d", nrow(test_set)))
print(sprintf("Train set size: %d", nrow(train_set)))
```
```{r}
colnames(train_set)
```


```{r}
#new df with necessary variables
train_set_1 <- train_set%>% 
  select(c(2, 5, 6, 12:30, 31, 32,33,34,38, 43,44,47, 49, 50, 51,52, 53,46)) %>%
  drop_na()

test_set_1<- test_set %>% 
  select(c(2, 5, 6, 12:30, 31, 32,33,34,38, 43,44,47, 49, 50, 51,52, 53,46)) %>%
  na.omit()

#ensure no nas
na_detect <- test_set_1 %>% filter(if_any(everything(), is.na))
summary(train_set_1)
```

## check for data validity

```{r} 
#date distribution
ggplot(data = train_set_1, aes(x = day_of_week)) + 
  geom_line(stat = "count", color = "black")+
  labs(title = "date distribution", x = "date", y = "number of available date on this date")
```


```{r}
ggplot(data = test_set_1, aes(x = day_of_week)) + 
  geom_line(stat = "count", color = "black")+
  labs(title = "date distribution", x = "date", y = "number of available date on this date")
```

```{r}
#numerical distribution & outlier detection
price_train <- ggplot(data = train_set_1, aes(x = `Ticket Price Min USD`)) +
    geom_histogram(binwidth = 5, fill = "blue",color = "black")
price_train
```



```{r}
#numerical distribution & outlier detection
price_test <- ggplot(data = test_set_1, aes(x = `Ticket Price Min USD`)) +
    geom_histogram(binwidth = 5, fill = "blue",color = "black")
price_test
```

```{r, eval = T}
#convert to numerical 
number_convertion_by_comma <- function(str){
  if(grepl(", ", str)){
    return(length((unlist(strsplit(str, ", ")))))
    
  }
  else{return (1)}
}
```

```{r, eval = T}
test = train_set_1$Promoter
test = sapply(test, number_convertion_by_comma)
train_set_1$Promoter = test
train_set_1$Promoter = as.integer(train_set_1$Promoter)

unique(train_set_1$Promoter)

test_1 = test_set_1$Promoter
test_1 = sapply(test_1, number_convertion_by_comma)
test_set_1$Promoter = test_1
test_set_1$Promoter = as.integer(test_set_1$Promoter)
unique(test_set_1$Promoter)
```

## Model Selection, stepwise regression


```{r, eval = T}
df3 = select(train_set_1, c(2,3, 6,7,21:26,28, 30,31:32,34,35,36))
df3$day_of_week <- as.factor(df3$day_of_week)
df3$Month <-as.factor(df3$Month)
Full = lm(data = df3, `Avg. Gross USD` ~.)
MSE = (summary(Full)$sigma)^2
model = step(Full, scope=list(upper=Full),scale=MSE)

RMSE = sqrt(summary(model)$sigma^2)
summary(model)
summary(model)$r.squared
RMSE
```


### check VIF and skewness
```{r}
vif(model)
```

```{r, eval = T}
plot(model,c(1,2,5))
```



#Cross validation

```{r}
train_model <- function(x,y){
  full = lm(data = cbind(x,y), y ~.)
  full_mse = (summary(full)$sigma)^2
  Model <- step(full, scope=list(upper=full),scale=full_mse) 
  return (Model)
}
```


```{r}
x_train = df3 %>% 
  select(-c(17))
folds <- sample(1: 5, size = nrow(x_train), replace = TRUE)
y_train = df3 %>%
  pull(c(17))
rmse_score <- numeric(5)
r2_score <- numeric(5)
```

```{r}
for (k in 1:5){
  train_index <- which(folds != k)
  test_index <- which(folds == k)
  X_train_fold <- x_train[train_index, ]
  y_train_fold <- y_train[train_index]
  X_test_fold <- x_train[test_index, ]
  y_test_fold <- y_train[test_index]
  
  models <- train_model(X_train_fold, y_train_fold)
  
  y_pred <- predict(model, newdata = X_test_fold)
  
  rmse_score[k] <- sqrt((summary(models)$sigma)^2)
  ss_total <- sum((y_test_fold - mean(y_train_fold))^2)
  ss_residual <- sum((y_test_fold - y_pred)^2)
  r2_score[k] <- 1 - (ss_residual / ss_total)
  
}


cat("Cross-validation RMSE scores:", round(rmse_score, 3), "\n")
cat("Mean CV RMSE:", round(mean(rmse_score), 3), "\n")
cat("Cross-validation R² scores:", round(r2_score, 3), "\n")
cat("Mean CV R²:", round(mean(r2_score), 3), "\n")
```



#Check for performance

```{r}

test_set_1$Month <- as.factor(test_set_1$Month)
test_set_1$day_of_week <- as.factor(test_set_1$day_of_week)
test_data = predict(model, newdata = test_set_1)
test_res = test_set_1$`Avg. Gross USD` - test_data
# mean(test_res)
# sd(test_res)


crosscorr=cor(test_set_1$`Avg. Gross USD`,test_data)
r_squ = crosscorr^2

RMSE_test <- sqrt(mean(test_res^2))

#Change in r^2 from the training to the holdout(3%)
shrinkage = summary(model)$r.squared-crosscorr^2

r_squ
RMSE_test

```







## forward

```{r}
none = lm(data = df3, `Avg. Gross USD` ~ 1)

# Using step() and direction="forward" to do forward selection
forward_model = step(none, scope=list(upper=Full), scale=MSE, direction="forward", trace = FALSE)
RMSE_forward = sqrt(summary(forward_model)$sigma^2)
summary(forward_model)
summary(forward_model)$r.squared
RMSE_forward
forward_model
```

```{r}
test_data_forward = predict(forward_model, newdata = test_set)
test_res = test_set$`Avg. Gross USD` - test_data_forward
# mean(test_res)
# sd(test_res)


crosscorr_forward=cor(test_set$`Avg. Gross USD`,test_data_forward)
r_squ_forward = crosscorr_forward^2

RMSE_forward <- sqrt(mean(test_res^2))

#Change in r^2 from the training to the holdout(3%)
shrinkage_forward = summary(forward_model)$r.squared-crosscorr_forward^2

r_squ_forward
RMSE_forward
```
```{r}
df4 <- df3 %>% select(-c(`Month`, `day_of_week`))
str(df3)
colnames(df3)
corrplot(cor(df4), type="upper")
```

